### ISSUE TITLE
module_with_calls is not public caused I failed to compose two calls

### ISSUE THREAD

**Issue by Dengjianping** [paritytech/substrate-subxt#112]
Hi there,

This issue might be quite the same with [How could I send a sudo call](https://github.com/paritytech/substrate-subxt/issues/84). 

I'm using subxt-0.6, which works fast and as expected. But I find out that this interface [module_with_calls](https://github.com/paritytech/substrate-subxt/blob/master/src/metadata.rs#L92) become private while I try to upgrade to 0.7. Here is code sample with subxt-0.6
```rust
let proposal = client.metadata().module_with_calls("MyModule")
		.and_then(|module| module.call("my_call", my_call_args))
		.map_err(|_| crate::Error::SubxtError("failed to compose a sudo call"))?;
let call = Call::new("Sudo", "sudo", proposal);
```

So now I cannot upgrade subxt to 0.7 or higher, can that interface change to be public? Or maybe you can give me a better solution instead of changing that interface.

Thanks!

**Comment by dvc94ch** [comment]
You should look at the examples, for example the frame/balances module.

**Comment by Dengjianping** [comment]
Yes, those examples are really good. I checked it, but it's not meet my requirements.
I have a my own module, and one of call from this module still needs sudo privilege, so I didn't find any example that can send a sudo call.
But in subxt-0.6, I can compose a sudo call as listed above, and it works.

**Comment by dvc94ch** [comment]
I see, so you want to construct an extrinsic and pass it as the argument to another extrinsic. I think #113 could help with that, but I'd need to try it.
