### ISSUE TITLE
Misusing the proc macros gives poor error messages

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate-subxt#122]
Misusing the proc macros results in very unhelpful error messages.  I have seen:

- Unwrapping `None`
- Undefined variables with no explanation
- Probably others

Furthermore, the correct use of the proc macros is poorly documented.  I had to figure it out by trial and error.

**Comment by dvc94ch** [comment]
the `proc-macro-error` crate is nice. I used it in a proc-macro today, really makes for a better ux. it should be easy to move to start using it, just replace `panic!` with `abort!` and `unwrap` with `unwrap_or_else(|| abort!)`
