### ISSUE TITLE
`Treasury::Deposit` event can't be decoded

### ISSUE THREAD

**Issue by niklasad1** [paritytech/substrate-subxt#124]
`Treasury::Deposit` can't be decoded, see log below:

```bash
[2020-06-22T09:16:51Z DEBUG substrate_subxt::events] received event 'Treasury::Deposit'
Error: Events(TypeSizeUnavailable("Balance"))
```
AFAIK, this could be fixed by register `Balance` in `EventsDecoder::new`. Why isn't it?

**Comment by dvc94ch** [comment]
We can't know at compile time all the modules or events or types that might be used by an arbitrary runtime. The way it is intended to work is each module has a generated method with_#module that can be used to register the types. The events that can be emitted by an extrinsic are the ones defined by the module or modules it depends on. So trait Treasury: Balances + System, will make sure that both the types of the Balances and the System module are loaded.

When watching events this might be trickier, looking into a better api for watching events is on my to-do list.

Some of my assumptions might be wrong, so if you can help shed light onto the issue, that would be cool. Hopefully @ascjones metadata info work will be finished soon, it should help improve the situation.

**Comment by ascjones** [comment]
@niklasad1 can you give a bit more detail: which extrinsic and to which chain?

**Comment by niklasad1** [comment]
Thanks for the answer

I'm playing around with my custom runtime for `Intel Sgx` and when the node dispatched a call that involves fees (i.e, signed call) then the `treasury event` gets generated and the event could not be decoded.

The problem was that I had this:

```rust
#[module]
pub trait SgxEnclave: System {}
```

Which was fixed by (as @dvc94ch pointed out):

```rust
#[module]
pub trait SgxEnclave: System + Balances {}
```
