### ISSUE TITLE
Need 'fetch all the values in a map'

### ISSUE THREAD

**Issue by Lawliet-Chan** [paritytech/substrate-subxt#144]
Many times, we need to fetch all the values in a map. But now subxt only supports fetch one value by key. 
Can you support this function?

**Comment by 4meta5** [comment]
You could write a method that gets an iterator (using `frame_support::storage::IterableStorageMap`) over the map and collects all the values into a vector. Then use substrate-subxt to call that method.

**Comment by 4meta5** [comment]
Closed in https://github.com/paritytech/substrate-subxt/pull/148
