### ISSUE TITLE
An attempt to remove ModuleCalls in srml/mod.rs and relevant parts

### ISSUE THREAD

**Issue by daogangtang** [paritytech/substrate-subxt#15]
In original implementation, there needs ModuleCalls to delegate the call of those srml module, I think this is owed to the problem of the project structure. 

This design leads to a severe problem: if user of this library wants to introduce a new runtime module, he needs to impl ModuleCalls directly in his module file, and this is prevented by Rust for orphan rule.

So, I just do some changes for it. If we can agree on this approach, I will make a PR on it.

Thank you.

Ref: https://github.com/daogangtang/substrate-subxt/tree/master/src

**Comment by daogangtang** [comment]
PR at here: #16

**Comment by ascjones** [comment]
Should be fixed by #24
