### ISSUE TITLE
Intermittent CI failure: pure virtual method called 

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate-subxt#178]
Intermittently, all tests pass but the CI job fails with `pure virtual method called`.

Could be related: https://github.com/openethereum/openethereum/issues/6762, https://github.com/facebook/rocksdb/issues/649.

Perhaps because of the test node, which probably uses rocksdb.

**Comment by gregdhill** [comment]
Any update on this? We're using the test runner in [polkabtc-clients](https://gitlab.com/interlay/polkabtc-clients) and we encounter this failure quite consistently.

**Comment by ascjones** [comment]
No I haven't had the chance to look at it yet, it is extremely annoying though.

**Comment by sander2** [comment]
Fwiw, in `polkabtc-clients`, using ParityDb instead of RocksDb in the tests seems to work around this issue

**Comment by ascjones** [comment]
Integration tests on our CI now use a spawned node rather than the embedded `test-node`. See #252. I'll close this for now, even though it using the `test-node` on CI will still produce this error.
