### ISSUE TITLE
Can not decode types with variable length encoding.

### ISSUE THREAD

**Issue by Recmo** [paritytech/substrate-subxt#181]
I have an event that contains a public key as an elliptic curve point, which looks roughly like this:

```rust
enum PublicKey {
   Zero, // default
   Point {
      x: U256.
      y: U256,
   }
}
```

When I register it using `register_type_size<PublicKey>("PublicKey")`*, I can successfully decode events containing Zero values, but non-zero values fail with:
```
Error: Scale codec error: Not enough data to fill buffer
```

On the other hand, if I force the type_size to the second case (which is 65 bytes encoded) using `register_type_size<(u8, [u8;32], [u8;32])>("PublicKey")` then I can sucessfully decode non-zero values but the Zero value fails with the above error.

How do I get event decoding to work in all cases?

*: PS: I'd like to use the `#[module]` macro, but it doesn't allow me to add types other than trait associated ones?

**Comment by h4x3rotab** [comment]
Currently subxt can only handle fix-size types. In `register_type_size`, it get the type by counting the byte length of `T::encode(Default::default())`.
