### ISSUE TITLE
how can we use own key ?

### ISSUE THREAD

**Issue by LayNath242** [paritytech/substrate-subxt#183]
let signer = PairSigner::new(AccountKeyring::Alice.pair());
how can we use own key pair

**Comment by Dengjianping** [comment]
My own usage.

```rust
use sp_core::{sr25519::Pair, Pair as TraitPair};
// ...

let pair = Pair::from_string(signer.as_ref(), None)?;
let signer = PairSigner::<DefaultNodeRuntime, Pair>::new(signer);
```

**Comment by LayNath242** [comment]
thank you very much!
but 
let pair = Pair::from_string(signer.as_ref(), None)?;
where we can get signer

**Comment by Dengjianping** [comment]
You can deserialize a dest by serde_json.
```rust
let dest = sp_runtime::AccountId32::from_str("5G9VdMwXvzza9pS8qE8ZHJk3CheHW9uucBn9ngW4C1gmmzpv")?;
```

**Comment by LayNath242** [comment]
Thank you very much !

**Comment by LayNath242** [comment]
but because  type Address = pallet_indices::address::Address<Self::AccountId, u32>; use this
so when i use let dest = sp_runtime::AccountId32::from_str("5H46MDwrjxoysLcLt2grvTsDDLnjpx6NJJs3VqpkeZ67DenZ")?; 

it error expected enum `pallet_indices::address::Address`, found struct `sp_core::crypto::AccountId32

**Comment by Dengjianping** [comment]
```rust
let addr: &pallet_indices::address::Address = &dest.clone().into();
```
It should work, but I don't give a try.

**Comment by LayNath242** [comment]
yes it work with
let dest = pallet_indices::address::Address::from(dest);
