### ISSUE TITLE
Integration with Substrate master branch

### ISSUE THREAD

**Issue by c410-f3r** [paritytech/substrate-subxt#220]
Is there a plan to update the current code-base to work with the master branch of Substrate? For example, a separated branch could be a good approach.
As things are now, `subtract-subxt` is incompatible with `cumulus` due to conflicting `substrate-*` dependencies.

**Comment by ascjones** [comment]
Yes the current substrate release is now very out of date. Will need to consider how best to do this.

**Comment by qqliaoxin** [comment]
When are you planning to update the version?

**Comment by qqliaoxin** [comment]
When will the version plan be updated?
