### ISSUE TITLE
Inconsistency with key generation vs subkey

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate-subxt#233]
We are experiencing inconsistency with subxt key generation and restoration.

Implementation: https://github.com/webb-tools/cli/blob/main/src/keystore.rs
Linking an issue we are running into: https://github.com/webb-tools/cli/issues/1

**Comment by ascjones** [comment]
Hi @drewstone, I see the linked issue is closed now - I will close this here now, Feel free to reopen if it is still unresolved.
