### ISSUE TITLE
Hardcoded jsonrpsee version to alpha3

### ISSUE THREAD

**Issue by akru** [paritytech/substrate-subxt#273]
Currently, Polkadot crates use jsonrpsee `>=0.2.0-alpha5` but subxt is fixed on alpha3. It makes it impossible to use subxt and polkadot in the same project.

It would be very helpful to upgrade the used jsonrpsee version up to the latest.

**Comment by niklasad1** [comment]
There is pending PR for that, https://github.com/paritytech/substrate-subxt/pull/266
