### ISSUE TITLE
Why not just use the existing types from the blockchain?

### ISSUE THREAD

**Issue by wuminzhe** [paritytech/substrate-subxt#281]
When I do a rpc to a dispatch call or get a storage, I need to define types for that dispatch call or storage.
If I can use the types from the chain directly, I will not need to define these types.

Are there any design considerations for this?

**Comment by ascjones** [comment]
Indeed, having to define your own copies of types is a problem: one I am currently working on solving via https://github.com/paritytech/substrate/pull/8615.

Ultimately we want this library to be a lightweight way to communicate with any version of any substrate chain, so direct substrate dependencies are not an option.

Once the above work is integrated into substrate, we should be able to generate all necessary types directly from the metadata.

**Comment by wuminzhe** [comment]
> Indeed, having to define your own copies of types is a problem: one I am currently working on solving via [paritytech/substrate#8615](https://github.com/paritytech/substrate/pull/8615).
> 
> Ultimately we want this library to be a lightweight way to communicate with any version of any substrate chain, so direct substrate dependencies are not an option.
> 
> Once the above work is integrated into substrate, we should be able to generate all necessary types directly from the metadata.

Great job. Thank you.
