### ISSUE TITLE
xt should return immediately

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/substrate-subxt#5]
Currently when submitting an extrinsic, the future doesn't resolve until the extrinsic is included in a block. The future should return immediately and ExtrinsicSuccess should expose a wait_block and wait_final which return futures.

**Comment by ascjones** [comment]
I believe this is closed by https://github.com/paritytech/substrate-subxt/pull/6

**Comment by dvc94ch** [comment]
Well there is still no nice method to wait so I wouldn't call it finished yet...
