### ISSUE TITLE
How to get the self-defined module state?

### ISSUE THREAD

**Issue by cezhang52111** [paritytech/substrate-subxt#64]
I do not know how to get the self-defined module state using this current version of subxt. I can only find the way of sending extrinsics. Will you consider adding this functionality of getting ledger state?

**Comment by gnunicorn** [comment]
what about https://github.com/paritytech/substrate-subxt/blob/3618b03dee7ee3dbd8e9d6108e32429932252c95/src/rpc.rs#L102 ?

**Comment by cezhang52111** [comment]
I still need to compute the StorageKey according to the self-defined module. What I mean is that to use string as the input, like get_storage("System", "AccountNonce");

**Comment by lucgerrits** [comment]
@cezhang52111 Hi, you closed the issue but can you give an example of the solution?
How did you code the Rust to build the StorageKey?

I'm trying to get the storage of a module/pallet with the metadata like this: 
```JSON
{
    "name": "MyModule",
    "storage": {
        "prefix": "MyModule",
        "entries": [
            {
                "name": "MyDataSet",
                "modifier": "Default",
                "ty": {
                    "Map": {
                        "hasher": "Blake2_128Concat",
                        "key": "T::AccountId",
                        "value": "(T::AccountId, T::BlockNumber)",
                        "unused": false
                    }
                }
            }
        ]
    }
}

```

**Comment by vyorkin** [comment]
Hi, I'm looking for example too. @lucgerrits Did you manage to find out anything related to your question above? Thank you
