### ISSUE TITLE
With the latest verision of Substrate, build failed

### ISSUE THREAD

**Issue by cezhang52111** [paritytech/substrate-subxt#69]
error[E0432]: unresolved import `sp_runtime::traits::SimpleArithmetic`
  --> src/frame/balances.rs:30:5
   |
30 |     SimpleArithmetic,
   |     ^^^^^^^^^^^^^^^^ no `SimpleArithmetic` in `traits`

error[E0432]: unresolved import `sp_runtime::traits::SimpleArithmetic`
  --> src/frame/system.rs:38:5
   |
38 |     SimpleArithmetic,
   |     ^^^^^^^^^^^^^^^^ no `SimpleArithmetic` in `traits`

I think this is due to the update of the substrate. Maybe we should add the rev of the substrate's github dependencies.

**Comment by ascjones** [comment]
> Maybe we should add the rev of the substrate's github dependencies.

It's annoying but tracking master forces to keep up to date with substrate. Once `substrate` releases `2.0` we can get some versions in and do some stable releases
