### ISSUE TITLE
Multisignature decoding error in submit_and_watch example

### ISSUE THREAD

**Issue by whalelephant** [paritytech/substrate-subxt#81]
I am unable to run the example with the following versions:
 
1. using substrate node version 2.0.0-alpha.5-beff53804-x86_64-macos
1. using release 0.5 of this repo

```
Error: Rpc(Request(Error { code: ServerError(1002), message: "Verification Error: Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\"))", data: Some(String("RuntimeApi(\"Execution(ApiError(\\\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\\\"))\")")) }))
```

**Comment by ascjones** [comment]
I've just tested it against the latest substrate `HEAD` (at the time of testing) https://github.com/paritytech/substrate/commit/fa71ce9cb3b814ec4d72e5b5bcefcec6097392fa, and it works okay for me.

Can you try again with a newer version of substrate? Although it should work with the version you specify too.

**Comment by whalelephant** [comment]
I think the problem is related to the binary I submitted the example extrinsic to. The error was found when I tried to submit to the `node-template` binary. There is no issue with the `substrate` binary. Not sure that the differences are since the example doesn't use the node-template test pallet. Will have a look and open issue on substrate repo if needed. Thanks!

**Comment by ascjones** [comment]
Yes it probably is. The `DefaultNodeRuntime` types assume you are using the full substrate `node-runtime`. The `KusamaRuntime` should work with the node-template runtime - see the example

**Comment by whalelephant** [comment]
Ah, I see now, the runtimes are different runtimes with different Address types.   Thanks!
