### ISSUE TITLE
Create raw payload from rpc client

### ISSUE THREAD

**Issue by whalelephant** [paritytech/substrate-subxt#82]
Hi,
I would like to get feedback on a proposed method for `Client` such that 
`client.create_raw_payload(AccountId, Call)` returns the payload to be signed.

The reason is so that the payload may be signed by other signers (maybe not in the `XtBuilder` and use this or other tools to create `uncheckedExtrinsic`.

**Comment by ascjones** [comment]
Sounds like a good idea, though perhaps it would be on the `XtBuilder` API?

**Comment by whalelephant** [comment]
From my understanding `Xtbuilder` currently accept a signer type with trait `Pair` implemented for signing. The proposed method is so that the only requirement for creating the raw payload is the pubkey / account ID

**Comment by ascjones** [comment]
Yeah you're right. Potentially could make signer `Option<P>` then provide an `XtBuilder` impl with `P = ()`. But feel free to make a PR with your idea, and we can see how it looks.

**Comment by whalelephant** [comment]
ok cool, I don't have permission to push my working branch for the PR at the moment. Please help. thanks!

**Comment by ascjones** [comment]
If you have a fork you should be able to push to that and create a PR from there

**Comment by ascjones** [comment]
Closed in #83
